### ISSUE TITLE
Error with interactive web demo & Penn Tree Bank

### ISSUE THREAD

**Issue by azpoliak** [hltcoe/PredPatt#1]
I just set up predpatt following the instructions but I get the following error message when I try loading the server in the browser. Do I need to have a local copy of the Penn Tree Bank?
<img width="1213" alt="screen shot 2017-02-21 at 11 24 30 am" src="https://cloud.githubusercontent.com/assets/3633302/23173833/70d14db2-f828-11e6-9c04-404718463077.png">

**Comment by sheng-z** [comment]
This is a JPype bug on Mac OS. Some solutions could be found by searching on the web.
