### ISSUE TITLE
New tutorial (ipynb) does not load on github

### ISSUE THREAD

**Issue by saraswat** [hltcoe/PredPatt#9]
Clicking on the link https://github.com/hltcoe/PredPatt/blob/master/tutorial.ipynb. You will see the page does not display. (Reloading does not help,)

**Comment by azpoliak** [comment]
I just clicked on the link in Chrome and the page is displayed for me. I am not able to run the notebook in the browser but I am definitely able to see it. 
Maybe its an issue related to your browser?

**Comment by sheng-z** [comment]
No followup for a while so I assume it's solved.
